# programmers = "jide" "divine" "micheal" "divine"
# programmer = "jide", "divine", "micheal", "juwon"
# programmerss = ("jide" "divine" "micheal" "juwon")
# programmerr = ("jide", "divine", "micheal", "juwon")
# programmersss = ["jide", "divine", "micheal", "juwon", "juwon"]
# # programmersss.append("ayo")
# programmersss.insert(1, "ayo")
# print(programmersss)




# programmer = ["jide", "divine", "micheal", "juwon"]
# programmers = ["jide", "fuwad", "juwon", "micheal", ]
# programmers.extend(programmer)
# print(programmers)





# programmer = ["jide", "divine", "micheal", "juwon"]
# programmers = ["jide", "moyin", "juwon", "micheal", ]
# programmer.extend(programmers)
# programmer[1]="sade" 
# programmer[3]="moon"
# programmer[6]="tolu"
# print(programmer)